name: DAVID CONWAY
favicon: null
layout_spectrum: 0.50781
typography_spectrum: 0.23892763536423445
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors: []
  brandStrength: 1
  lightness: 0.7547052288427949
  saturation: 0.7634959537535906
  rhythmicContrast: 0.7148311284836382
purpose: []
