name: DAVID CONWAY
favicon: null
layout_spectrum: 0.5
typography_spectrum: 0.5
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0F0B0C'
    - '#FBD780'
    - '#FFFFB6'
    - '#775C42'
    - '#9A5404'
  brandStrength: 1
  lightness: 0.9516129
  saturation: 0.9139785
  rhythmicContrast: 0.8512545
purpose: []
