name: DAVID CONWAY
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
purpose: []
color:
  saturation: 0.9139785
  lightness: 0.9516129
  brandStrength: 1
  brandColors:
    - '#0F0B0C'
    - '#FBD780'
    - '#FFFFB6'
    - '#775C42'
    - '#9A5404'
  rhythmicContrast: 0.8512545
typography_spectrum: 0.5
cta:
  bucket: null
  version: null
  domain: null
analytics:
  twitter: null
  google: null
  facebook: null
favicon: null
layout_spectrum: 0.5232975
